services:
  # postgres:
  #  image: akshitjain16/postgres:latest
  #   container_name: metasketch_postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 000000
  #     POSTGRES_DB: metasketch
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  http:
    image: akshitjain16/metaverse-community-http:latest
    # build:
    #   context: ./community
    #   dockerfile: ./apps/http/Dockerfile
    container_name: metasketch_http
    env_file:
      - .env 
    ports:
      - "3000:3000"

  ws:
    image: akshitjain16/metaverse-community-ws:latest
    # build:
    #   context: ./community
    #   dockerfile: ./apps/ws/Dockerfile
    container_name: metasketch_ws
    env_file:
      - .env
    ports:
      - "3001:3001"

  tests:
    image: akshitjain16/metaverse-community-tests:latest
    # build:
    #   context: .
    #   dockerfile: ./tests/Dockerfile
    container_name: metasketch_tests
    env_file:
      - .env           
    depends_on:
      - http
      - ws

volumes:
  postgres_data: