services:
  postgres:
    image: postgres:13
    container_name: metasketch_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000000
      POSTGRES_DB: metasketch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  http:
    build:
      context: ./community
      dockerfile: ./apps/http/Dockerfile
    container_name: metasketch_http
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 000000
      DB_NAME: metasketch
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: